=== grcmupc/portrait/O1/testing/measData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  3GPP TS 28.550 Measurements data XML file format definition
  data file XML schema
  measData.xsd
-->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:md="http://www.3gpp.org/ftp/specs/archive/28_series/28.550#measData" targetNamespace="http://www.3gpp.org/ftp/specs/archive/28_series/28.550#measData" elementFormDefault="qualified">
	<!-- Measurement collection data file root XML element -->
	<element name="MeasDataFile">
		<complexType>
			<sequence>
				<element name="fileHeader">
					<complexType>
						<sequence>
							<element name="fileSender">
								<complexType>
									<attribute name="senderName" type="string" use="optional"/>
									<attribute name="senderType" type="string" use="optional"/>
								</complexType>
							</element>
							<element name="MeasData">
								<complexType>
									<attribute name="beginTime" type="dateTime" use="required"/>
								</complexType>
							</element>
						</sequence>
						<attribute name="fileFormatVersion" type="string" use="required"/>
						<attribute name="vendorName" type="string" use="optional"/>
            				<attribute name="dnPrefix" type="string" use="optional"/>
					</complexType>
				</element>
				<element name="measData" minOccurs="0" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="measuredEntity">
								<complexType>
									<attribute name="userLabel" type="string" use="optional"/>
									<attribute name="localDn" type="string" use="optional"/>
									<attribute name="swVersion" type="string" use="optional"/>
								</complexType>
							</element>
							<element name="measInfo" minOccurs="0" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="job" minOccurs="0">
											<complexType>
												<attribute name="jobId" type="string" use="required"/>
											</complexType>
										</element>
										<element name="granPeriod">
											<complexType>
												<attribute name="duration" type="duration" use="required"/>
												<attribute name="endTime" type="dateTime" use="required"/>
											</complexType>
										</element>
										<element name="repPeriod" minOccurs="0">
											<complexType>
												<attribute name="duration" type="duration" use="required"/>
											</complexType>
										</element>
										<choice>
											<element name="measTypes">
												<simpleType>
													<list itemType="Name"/>
												</simpleType>
											</element>
											<element name="measType" minOccurs="0" maxOccurs="unbounded">
												<complexType>
													<simpleContent>
														<extension base="Name">
															<attribute name="p" type="positiveInteger" use="required"/>
														</extension>
													</simpleContent>
												</complexType>
											</element>
										</choice>
										<element name="measValue" minOccurs="0" maxOccurs="unbounded">
											<complexType>
												<sequence>
													<choice>
														<element name="measResults">
															<simpleType>
																<list itemType="md:measResultType"/>
															</simpleType>
														</element>
														<element name="r" minOccurs="0" maxOccurs="unbounded">
															<complexType>
																<simpleContent>
																	<extension base="md:measResultType">
																		<attribute name="p" type="positiveInteger" use="required"/>
																	</extension>
																</simpleContent>
															</complexType>
														</element>
													</choice>
													<element name="suspect" type="boolean" minOccurs="0"/>
												</sequence>
												<attribute name="measObjLdn" type="string" use="required"/>
											</complexType>
										</element>
									</sequence>
									<attribute name="measInfoId" type="string" use="optional"/>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
				<element name="fileFooter">
					<complexType>
						<sequence>
							<element name="MeasData">
								<complexType>
									<attribute name="endTime" type="dateTime" use="required"/>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
	<simpleType name="measResultType">
		<union memberTypes="integer float string">
			<simpleType>
				<restriction base="string">
					<enumeration value="NULL"/>
				</restriction>
			</simpleType>
		</union>
	</simpleType>
</schema>

=== grcmupc/portrait/O1/Sample_data/xml_PM_report_sample.xml
<?xml version="1.0" encoding="utf-8"?>
<md:MeasDataFile xmlns:md="http://www.3gpp.org/ftp/specs/archive/28_series/28.550#measData" xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://www.3gpp.org/ftp/specs/archive/28_series/28.550#measData measData.xsd">>
  <md:fileHeader fileFormatVersion="28.550 V16.0" vendorName="" dnPrefix="">
    <md:fileSender senderName="Cell1" senderType="O-DU" /> 
    <md:MeasData beginTime="2022-07-01T08:00:00" />
  </md:fileHeader>
  <md:measData>
    <md:measuredEntity userLabel="NRCell0" localDn="" swVersion="" />
    <md:measInfo measInfoId="RRU_block">
      <md:job jobId="job0001" />
      <md:granPeriod duration="PT900S" endTime="2021-12-01T08:15:00" />
      <md:repPeriod duration="PT900S" />
      <md:measType p="1" >RRU.PrbUsedDl.1</md:measType>
      <md:measType p="2" >RRU.PrbUsedDl.2</md:measType>
      <md:measType p="3" >RRU.RRU.PrbAvailDl</md:measType>
      <md:measValue measObjLdn="">
       <md:r p="1">20</md:r>
       <md:r p="2">25</md:r>
       <md:r p="3">20</md:r>
        <md:suspect>true</md:suspect>
      </md:measValue>
    </md:measInfo>
    <md:measInfo measInfoId="QoSFlow_block">
      <md:job jobId="job0002" />
      <md:granPeriod duration="PT900S" endTime="2021-12-01T08:15:00" />
      <md:repPeriod duration="PT900S" />
      <md:measType p="4" >QosFlsow.PdcpPduVolumeDL.1</md:measType>
      <md:measType p="5" >QosFlow.PdcpPduVolumeDL.2</md:measType>
      <md:measValue measObjLdn="">
       <md:r p="4">32327</md:r>
       <md:r p="5">40751</md:r>
        <md:suspect>true</md:suspect>
      </md:measValue>
    </md:measInfo>
  </md:measData>
  <md:fileFooter>
    <md:MeasData endTime="2022-07-01T08:15:00" />
  </md:fileFooter>
</md:MeasDataFile>
